export const VIDEO = {
  FIELD_INITIALIZER: 'FIELD_INITIALIZER',
  GET_MATERIAL_VIDEO_ITEM: {
    MAIN: 'GET_MATERIAL_VIDEO_ITEM',
    SUCCESS: 'GET_MATERIAL_VIDEO_ITEM_SUCCESS',
    FAILURE: 'GET_MATERIAL_VIDEO_ITEM_FAILURE',
    MEDIA: 'GET_MATERIAL_VIDEO_ITEM_MEDIA'
  },
  UPDATE_VIDEO_TITLE: {
    MAIN: 'UPDATE_VIDEO_TITLE',
    SUCCESS: 'UPDATE_VIDEO_TITLE_SUCCESS',
    FAILURE: 'UPDATE_VIDEO_TITLE_FAILURE'
  },
  YOUTUBE_CHANNELS_CATEGORIES: {
    MAIN: 'UPDATE_VIDEO_TITLE',
    SUCCESS: 'YOUTUBE_CHANNELS_CATEGORIES_SUCCESS',
    FAILURE: 'YOUTUBE_CHANNELS_CATEGORIES_FAILURE'
  },
  VIMEO_PRIVACY_LIST: {
    MAIN: 'VIMEO_PRIVACY_LIST',
    SUCCESS: 'VIMEO_PRIVACY_LIST_SUCCESS',
    FAILURE: 'VIMEO_PRIVACY_LIST_FAILURE'
  },
  VIDEO_SAVE_YOUTUBE: {
    MAIN: 'VIDEO_SAVE_YOUTUBE',
    SUCCESS: 'VIDEO_SAVE_YOUTUBE_SUCCESS',
    FAILURE: 'VIDEO_SAVE_YOUTUBE_FAILURE'
  },
  GET_YOUTUBE_ITEM: {
    MAIN: 'GET_YOUTUBE_ITEM',
    SUCCESS: 'GET_YOUTUBE_ITEM_SUCCESS',
    FAILURE: 'GET_YOUTUBE_ITEM_FAILURE'
  },
  DELETE_VIDEO_CONTENT: {
    MAIN: 'DELETE_VIDEO_CONTENT',
    SUCCESS: 'DELETE_VIDEO_CONTENT_SUCCESS',
    FAILURE: 'DELETE_VIDEO_CONTENT_FAILURE'
  },
  VIDEO_SAVE_VIMEO: {
    MAIN: 'VIDEO_SAVE_VIMEO',
    SUCCESS: 'VIDEO_SAVE_VIMEO_SUCCESS',
    FAILURE: 'VIDEO_SAVE_VIMEO_FAILURE'
  },
  GET_VIMEO_ITEM: {
    MAIN: 'GET_VIMEO_ITEM',
    SUCCESS: 'GET_VIMEO_ITEM_SUCCESS',
    FAILURE: 'GET_VIMEO_ITEM_FAILURE'
  }
};
