import config from '../config';
const ApiServices = {
  TEST_API: 'tags',
  CONTENT_USERT_LIST: 'api/article/user/filter_list',
  USERT_LIST: 'api/user/list',
  CHECK_REGISTRATION_USERNAME_URL: 'api/user/register/check/username/',
  CHECK_PASSSWORD_STRENGTH: 'api/auth/password_strength_check/',
  USER_REGISTER: 'api/user/register',
  GET_PROFILE: 'api/user/profile/edit/',
  UPDATE_PROFILE: 'api/user/profile/update/',
  CHECK_USERNAME: 'api/user/check/username',
  GET_ROLE_LIST: 'api/roles/list',
  USERS_BLOCK_UNBLOCK: 'api/user/status/update',
  AUTH_LOGIN: 'api/auth/login',
  AUTH_FORGOT: 'api/auth/password/email',
  PASSWORD_STRENGTH_CHECK: 'api/auth/password_strength_check/',
  RESET_PASSWORD: 'api/auth/password/reset',
  USER_INVITE: 'api/user/invite',
  USER_ADD : 'api/user/add',
  GET_SNS_SETTING_LIST: 'api/sns/settings/list',
  SAVE_SNS_SETTING_LIST: 'api/sns/settings/save',
  GET_MEDIA_SETTING_LIST: 'api/media/settings/list',
  SAVE_MEDIA_SETTING_LIST: 'api/media/settings/save',
  GET_YOUTUBE_AUTHENTICATION : 'api/video/youtube/authenticate',
  EDIT_USER_GET_DETAILS: 'api/user/edit/',
  EDIT_USER_UPDATE_DETAILS: 'api/user/update/',
  VERIFY_EMAIL_TOKEN: 'api/user/verify/',
  PERMISSION_LIST: 'api/permissions/list',
  DEFAULT_PERMISSION: 'api/roles/permissions/default',
  UPDATE_PERMISSION: 'api/roles/permissions/update',
  GET_RAW_MATERIAL_VIDEO_LIST: 'api/video/list',
  POST_RAW_MATERIAL_VIDEO: '/api/video/upload',
  POST_VIDEO_MULTIPLE: '/api/video/upload/multiple',
  GET_MATERIAL_VIDEO_ITEM: 'api/video',
  GET_MATERIAL_MEDIA: 'api/media',
  UPDATE_URL_VIDEO_TITLE: 'api/video/update/title',
  YOUTUBE_CHANNELS_CATEGORIES_PATH: 'api/video/youtube/info',
  VIDEO_SAVE_YOUTUBE_PATH: 'api/video/youtube/upload',
  UPDATE_VIDEO_YOUTUBE_PATH: 'api/video/youtube/update',
  SHOW_VIDEO_YOUTUBE_PATH: 'api/video/youtube/show',
  DELETE_YOUTUBE_VIDEO_PATH: 'api/video/youtube/delete',
  DELETE_VIMEO_VIDEO_PATH: 'api/video/vimeo/delete',
  DELETE_NEWSCLOUD_VIDEO_PATH: 'api/video/delete',
  GET_CONTENT_LIST: 'api/article/contents/list',
  VIMEO_PRIVACY_LIST_PATH: 'api/video/vimeo/privacy/list',
  SAVE_VIMEO_DATA_PATH: 'api/video/vimeo/upload',
  UPDATE_VIMEO_DATA_PATH: 'api/video/vimeo/update',
  SHOW_VIDEO_VIMEO_PATH: 'api/video/vimeo',
  SAVE_ARTICLE: 'api/article/save',
  GET_CATEGORY_LIST: 'api/article/categories',
  CHECK_ARTICLE_TITLE: (title) => `api/article/unique?title=${title}`,
  CHECK_ARTICLE_URL: (slug) => `api/article/url/check?url=${slug}`,
  GET_UNIQUE_URL: 'api/article/url/get',
  UPDATE_ARTICLE: (id) => `api/article/update/${id}`,
  GET_ARTICLE: (id) => `api/article/list/${id}`,
  GET_EMAIL_GROUP_LIST: 'api/mailmagazine/group/list',
  OWN_MEDIA: (id) => `api/ownmedia/details/1`,
  OWN_MEDIA_ALL: 'api/ownmedia/all',
  MEDIA_LIST: 'api/video/media/list',
  GET_MEMBER_LIST_PATH: 'api/member/list',
  ADD_MEMBER_PATH: 'api/member/add',
  UPDATE_MEMBER_PATH: 'api/member/update',
  GET_MEMBER_ITEM_PATH: 'api/member/edit',
  DELETE_MEMBER_ITEM_PATH: 'api/member/delete',
  GET_USER_LIST: 'api/article/user/list',
  SAVE_COMMENT: 'api/article/comments/save',
  GET_ALL_COMMENT: (articleId) => `api/article/comments/${articleId}`,
  GET_REVIEWER_LIST: (id) => `api/article/users?role=${id}`,
  MEMBER_FILE_DOWNLOAD_PATH: 'api/member/csv/download',
  ADD_NEW_GROUP: 'api/mailmagazine/group/store',
  DELETE_MAIL_GROUP: 'api/mailmagazine/group/delete',
  GET_MAIL_GROUP_DETAILS: 'api/mailmagazine/group/get/',
  UPDATE_MAIL_GROUP: 'api/mailmagazine/group/update/',
  GET_GROUP_MEMBER_LIST: 'api/mailmagazine/member/list/',
  DELETE_MEMBER_FROM_GROUP_MAIL: 'api/mailmagazine/member/delete',
  ADD_NEW_GROUP_MEMBER: 'api/mailmagazine/member/store',
  EDIT_GROUP_MEMBER: 'api/mailmagazine/member/get/',
  UPDATE_GROUP_MEMBER_INFO: 'api/mailmagazine/member/update/',
  MAIL_GROUP_LIST_CSV_DOWNLOAD: 'api/mailmagazine/member/download/csv/',
  GET_MAIL_HISTORY_LIST: 'api/mailmagazine/email/history/list',
  GET_MAIL_HISTORY_DETAILS: 'api/mailmagazine/email/history/details/list/',
  CHECK_GROUP_MAIL_EXISTS: 'api/mailmagazine/group/name/check',
  EMAIL_HISTORY_DETAILS_CSV_DOWNLOAD:
    'api/mailmagazine/email/history/details/download/csv/',
  EMAIL_HISTORY_BODY_CONTENT: 'api/mailmagazine/email/history/mail/content/',
  EMAIL_HISTORY_DELETE : 'api/mailmagazine/email/history/delete',
  GROUP_MAIL_MEMBER_CSV_UPLOAD : 'api/mailmagazine/member/upload/csv/',
  REQUEST_REVIEW: (userId, articleId) =>
    `api/article/reviewer/notify?userId=${userId}&articleId=${articleId}`,
  REQUEST_APPROVAL: (userId, articleId) =>
    `api/article/approver/notify?userId=${userId}&articleId=${articleId}`,
  DELETE_ARTICLE: (articleId) => `api/article/delete/${articleId}`,
  INVITE_MEMBER_PATH: 'api/member/invite',
  CSV_UPLOAD_PATH: 'api/member/csv/upload',
  CSV_DELETE_PATH: 'api/member/csv/delete',
  MEMBER_UNIQUE_PATH: 'api/member/check/unique',
  GET_NOTIFICATIONS: 'api/article/notification/list',
  READ_NOTIFICATION: `api/article/notification/mark/as/read`,
  UPLOAD_IMAGE: 'api/article/images/upload',
  REMOVE_IMAGE: 'api/article/image/delete',
  CHECK_MAIL_MAGAZINE_MEMBER_EMAIL_UNIQUE: 'api/mailmagazine/member/email/check',
  YOUTUBE_TITLE_UNIQUE: 'api/video/youtube/check/unique',
  VIMEO_TITLE_UNIQUE: 'api/video/vimeo/check/unique',
  BULK_USER_INVITATION : 'api/user/invite',
  CHECK_USER_EMAIL_EXISTS : 'api/user/check/email',
  MAIL_POSTING_SAVE: 'api/article/mail/post',
  CLEAR_NOTIFICATION: 'api/article/notification/mark/as/clear',
  MAIL_SEND_STATUS: (email_history_id) => `api/article/mail/check/${email_history_id}`,
  MAIL_POSTING_UPDATE: (id) => `api/article/mail/post/${id}`,
  GET_MAIL_POSTING: (id) => `api/mailmagazine/email/history/list/${id}`,
  ADD_NEW_ROLE : 'api/role/store',
  UPDATE_ROLE : 'api/role/update/',
  DELETE_USER : 'api/user/delete/',
  GOOGLE_ANALYTIC_DATA:'api/statistic/settings/list',
  SAVE_GOOGLE_ANALYTIC_DATA : 'api/statistic/settings/save',
  SNS_POST_SAVE: 'api/sns/postings/post',
  SNS_POST_UPDATE: (id) => `api/sns/postings/post/${id}`,
  SNS_POST_GET: (articleId, platformId) => `api/sns/postings/post/show/data/${articleId}/${platformId}`,
  SNS_DELIVERY_CHECK: (id) => `api/sns/postings/post/check/${id}`,
  CREDENTIALS_CHECK_YOUTUBE_ANALYTICS_GOOGLE_ANALYTICS_AND_SEARCH_CONSOLE: `api/statistic/settings/check`,
  OWN_MEDIA_SITE_VIEWS: (startDate, endDate, processedBy) => `api/statistic/site/views?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}`,
  OWN_MEDIA_SITE_VISITORS: (startDate, endDate, processedBy) => `api/statistic/site/vistors?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}`,
  OWN_MEDIA_TRANSITION_VIEWS: (startDate, endDate, processedBy) => `api/statistic/site/transition-views?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}`,
  OWN_MEDIA_TRANSITION_VISITS: (startDate, endDate, processedBy) => `api/statistic/site/transition-visits?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}`,
  OWN_MEDIA_AVERAGE_VIEW: (startDate, endDate, processedBy) => `api/statistic/site/average-page-views?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}`,
  OWN_MEDIA_AVERAGE_STAYTIME: (startDate, endDate, processedBy) => `api/statistic/site/average-stay-time?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}`,
  OWN_MEDIA_SOURCE_ROUTE: (startDate, endDate, processedBy) => `api/statistic/site/source-route-site?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}`,
  OWN_MEDIA_SOURCE_REFERENCE: (startDate, endDate, processedBy, pagination) => `api/statistic/site/source-reference?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}&pagination=${pagination}`,
  OWN_MEDIA_VISITORS: (startDate, endDate, processedBy) => `api/statistic/visitor/new-return-visits?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}`,
  OWN_MEDIA_VISITOR_TRANSITION_OF_VISITOR: (startDate, endDate, processedBy) => `api/statistic/visitor/transition-new-return-visits?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}`,
  OWN_MEDIA_VISITOR_AGE: (startDate, endDate, processedBy) => `api/statistic/visitor/age?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}`,
  OWN_MEDIA_VISITOR_SEX: (startDate, endDate, processedBy) => `api/statistic/visitor/sex?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}`,
  OWN_MEDIA_VISITOR_DEVICE: (startDate, endDate, processedBy) => `api/statistic/visitor/device?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}`,
  OWN_MEDIA_CONTENT_PAGE_VIEWS: (startDate, endDate, processedBy, pagination) => `api/statistic/content/page-views-users-avg-time-on-page?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}&pagination=${pagination}`,
  OWN_MEDIA_KEYWORD_SEARCH_CONSOLE: (startDate, endDate, processedBy, pagination) => `api/statistic/search-console/keywords-clicks-displays-positions?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}&siteUrl=${config.GOOGLE_SEARCH_CONSOLE_SITE_URL}&pagination=${pagination}`,
  OWN_MEDIA_VISITOR_COUNTRY: (startDate, endDate, processedBy, pagination) => `api/statistic/visitor/country?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}&pagination=${pagination}`,
  OWN_MEDIA_VISITOR_CITY: (startDate, endDate, processedBy, pagination) => `api/statistic/visitor/city?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}&pagination=${pagination}`,
  YOUTUBE_SUMMERY_VIEWS: (startDate, endDate, processedBy) => `api/statistic/youtube/summary/views?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}`,
  YOUTUBE_SUMMERY_EVALUATION_LIKE: (startDate, endDate, processedBy) => `api/statistic/youtube/summary/evaluations?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}`,
  YOUTUBE_SUMMERY_TRAFFIC_SOURCE: (startDate, endDate, processedBy) => `api/statistic/youtube/summary/traffic-source?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}`,
  YOUTUBE_SUMMERY_RANK_OF_VIEWS: (startDate, endDate, processedBy, pagination) => `api/statistic/youtube/summary/rank-views?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}&pagination=${pagination}`,
  YOUTUBE_AVERAGE_VIEW_TIME: (startDate, endDate, processedBy) => `api/statistic/youtube/summary/average-view-time?startDate=${startDate}&endDate=${endDate}&processedBy=${processedBy}`,
  GOOGLE_CONSOLE_AUTHENTICATION : 'api/statistic/search-console/authenticate',
  VIDEO_TRACKING_FOR_LOGGER: (videoId, articleId) => articleId ? `api/article/insert/video/track?videoId=${videoId}&articleId=${articleId}` : `api/article/insert/video/track?videoId=${videoId}`,
  GET_PERMISSIONS: 'api/permissions/list/by/user'
};
export default ApiServices;
