const path = {
  home: '/',
  notFound: '/404',
  login: '/login',
  forgot: '/forgot-password',
  reset: '/reset-password',
  signup: '/registration',
  users: '/users',
  unauthorized: '/unauthorized',
  profile: '/profile',
  content: '/content',
  contentEdit: '/edit-content',
  contentCreate: '/new-content',
  contentCopy: '/copy-content',
  contentPreview: '/preview-content',
  public: '/public',
  statisticsOwnMedia: '/statistics-ownmedia',
  statisticsVideo: '/statistics-video',
  rawMaterials: '/raw-materials',
  systemSettings: '/system-settings',
  editUser: '/edit-user',
  mailHistory: '/mail-history',
  mailHistoryDetails: '/mail-history-details',
  mailGroup: '/mail-group',
  groupMailList: '/group-mail-list',
  memberList: '/member-lists',
  memberPermission: '/member-permissions',
  videoManagement: '/video-management',
  memberSave: '/member/save',
  role: '/role-settings',
  sns: '/sns-settings',
  location: '/location-settings',
  tokenExpired: '/token-expired',
  systemStatistics : '/statistics-setting'
};

export default path;
