export const MEMBER = {
  FIELD_INITIALIZATION: 'FIELD_INITIALIZATION',
  GET_MEMBER_LIST: {
    MAIN: 'GET_MEMBER_LIST',
    SUCCESS: 'GET_MEMBER_LIST_SUCCESS',
    FAILURE: 'GET_MEMBER_LIST_FAILURE'
  },
  GET_MEMBER_ITEM: {
    MAIN: 'GET_MEMBER_ITEM',
    SUCCESS: 'GET_MEMBER_ITEM_SUCCESS',
    FAILURE: 'GET_MEMBER_ITEM_FAILURE'
  },
  SAVE_MEMBER_ITEM: {
    MAIN: 'SAVE_MEMBER_ITEM',
    SUCCESS: 'SAVE_MEMBER_ITEM_SUCCESS',
    FAILURE: 'SAVE_MEMBER_ITEM_FAILURE'
  },
  MEMBER_ITEM_DELETE: {
    MAIN: 'MEMBER_ITEM_DELETE',
    SUCCESS: 'MEMBER_ITEM_DELETE_SUCCESS',
    FAILURE: 'MEMBER_ITEM_DELETE_FAILURE'
  },
  MEMBER_FILE_DOWNLOAD: {
    MAIN: 'MEMBER_FILE_DOWNLOAD',
    SUCCESS: 'MEMBER_FILE_DOWNLOAD_SUCCESS',
    FAILURE: 'MEMBER_FILE_DOWNLOAD_FAILURE'
  },
  MEMBER_FILE_UPLOAD: {
    MAIN: 'MEMBER_FILE_UPLOAD',
    SUCCESS: 'MEMBER_FILE_UPLOAD_SUCCESS',
    FAILURE: 'MEMBER_FILE_UPLOAD_FAILURE'
  },
  MEMBER_INVITATION: {
    MAIN: 'MEMBER_INVITATION',
    SUCCESS: 'MEMBER_INVITATION_SUCCESS',
    FAILURE: 'MEMBER_INVITATION_FAILURE'
  }
};
